{{ if not .Values.DremioAdmin }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio-monitor
spec:
  serviceName: "dremio-cluster-pod"
  podManagementPolicy: "Parallel"
  replicas: 0
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dremio-monitor
  template:
    metadata:
      labels:
        app: dremio-monitor
        role: dremio-cluster-pod
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: dremio-monitor
        image: amazon/aws-cli:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 1000M
            cpu: 1
        volumeMounts:
        - name: dremio-ephemeral
          mountPath: /mnt/ephemeral
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      volumes:
      - name: dremio-ephemeral
        hostPath:
          path: /mnt/ephemeral
{{ end }}